sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: oEd3nR5EsX6YqbTBS2zdcjY48CTQK5966wi5s0BGj7v8u9RXEJ0j3jQRbL3HJFmt89vxJp+oW72O904eL2+wOptoxLOVRAJDomuRsHW3pi9VMKvxFC5oayqZTKYEJpe7HcOTbQOzif+teNNyWza4XHwxRCOvQB4nkBDUrQNiMu1BlT4TCiscXfPay1UfsbI2mf3p1+SAayveLFOF4njY9ruaZkohGg60F0by66jYqpHQDO0OZs7Q27i2dzR/HxJfzDQTg+pbLeaemEGCgnS2O/k6s8NZGfcmIo44c/drCzW4wnL+tRBgyjfalZ/WZiN7XMcPIFlcgnSgxfH9u//t7Lm7zI5b6pVoccBAg9V/cR4pjWV5c62972uRIEmTZK0/uzJ1S977A62NK3HUUe3jmsvHhN6XxOIsrB3HyEcfgdGI4/lB+8WlGR4n59B+zlqkL2Rz+PJbDhg6Hqp6QtQL+J861CNxSrJgGBUfojht3NByvXPYIDOvrpcOXdx/bsqiGOhQfjJYUYoWvnmDUQ5OoaRA3TWvvg7Nv4lsSmORkKK0PTmOSiR6OHPM6TCSL8K3dsIloRACdbmOs4U/TaWTW8DbJcml6qbmSEawMTNiAOEsHkvJj9E95XEqbBvL/Xrf9o6Vwaoer3wGcm25mpltiXAZmzto51wQu9uW3FCDCpI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Blue-Moon_3527
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy